autocheck_name='Быстрая проверка стенда'

autocheck_vms='
    ISP    = exec_agent
    HQ-RTR = exec_serial
    HQ-SRV = exec_agent
    HQ-CLI = exec_agent
    BR-RTR = exec_serial
    BR-SRV = exec_agent
'

exec_serial_prompt='[A-Za-z0-9._-]+#'
exec_serial_timeout='5'
exec_serial_login='admin'
exec_serial_password='admin'
exec_serial_enable=true
exec_serial_enable_password=''
exec_serial_setup='terminal length 0'

check_1_name='Имя хоста'
check_1_vms='ISP HQ-SRV HQ-CLI BR-SRV'
check_1_cmd_exec_agent='hostname'

check_2_name='IP-адреса'
check_2_vms='ISP HQ-SRV HQ-CLI BR-SRV HQ-RTR BR-RTR'
check_2_cmd_exec_agent='ip -br a'
check_2_cmd_exec_serial='show ip interface brief'

check_3_name='Таблица маршрутизации'
check_3_vms='HQ-RTR BR-RTR'
check_3_cmd_exec_serial='show ip route'
