# Тестовая автопроверка: sh run на EcoRouter (HQ-RTR, BR-RTR)

autocheck_name='Тест serial: sh run'

autocheck_vms='
    HQ-RTR = exec_serial
    BR-RTR = exec_serial
'

exec_serial_prompt='[A-Za-z0-9._-]+[#>]'
exec_serial_timeout=10
exec_serial_login='admin'
exec_serial_password='admin'
exec_serial_enable=true
exec_serial_setup='terminal length 0'

check_1_name='Running config'
check_1_vms='HQ-RTR BR-RTR'
check_1_cmd_exec_serial='sh run'
